title: The Secret Pot HomeLab
description: This is a secret lab for those who truly believe in the glorious Pot supremacy. Try fingers but hole.
background:
  image: /images/homepage_bg.jpg
  blur: sm
cardblur: xs
